services:
    zertz.admin.blog.tag:
        class: Zertz\Blog\SortBundle\Admin\TagAdmin
        arguments: [null, Zertz\Blog\SortBundle\Entity\Tag, 'SonataAdminBundle:CRUD']
        calls:
            - [setTranslationDomain, [Zertz\Blog\SortBundle]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Blog, label: Tags }
